package br.org.roger.spring.domain;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * FlPreLancamentoTipo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "FL_PRE_LANCAMENTO_TIPO")
@NamedQueries({})
public class PreLancamentoTipo implements java.io.Serializable {

    public static final int VENDA = 1;
    public static final int CONDITIONAL = 2;
    public static final int SEM_LANCE = 3;

	public static final class Queries {
	}

	@Id
	@Column(name = "COD_TIPO_PRE_LANCAMENTO", unique = true, nullable = false, precision = 1, scale = 0)
	private Integer id;

	@Column(name = "DESCRICAO_TIPO_PRE_LANCAMENTO", length = 30)
	private String descricaoTipoPreLancamento;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "preLancamentoTipo")
	private Set<PreLancamento> preLancamentos = new HashSet<PreLancamento>(0);

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDescricaoTipoPreLancamento() {
        return descricaoTipoPreLancamento;
    }

    public void setDescricaoTipoPreLancamento(String descricaoTipoPreLancamento) {
        this.descricaoTipoPreLancamento = descricaoTipoPreLancamento;
    }

    public Set<PreLancamento> getPreLancamentos() {
        return preLancamentos;
    }

    public void setPreLancamentos(Set<PreLancamento> preLancamentos) {
        this.preLancamentos = preLancamentos;
    }
}
