package br.org.roger.spring.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelPortalEmailId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class RelPortalEmailId implements java.io.Serializable {

	public static final class Queries {
    }
    
 

    @Column(name="EREG_PORTAL_ID", nullable=false, precision=4, scale=0)
 	private short portalId;
 

    @Column(name="EMAIL_ID", nullable=false, precision=9, scale=0)
 	private int emailId; 	
 

    @Column(name="PORTAL_CONTACT_ID", nullable=false, precision=3, scale=0)
 	private short portalContactId;


	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;

		RelPortalEmailId that = (RelPortalEmailId) o;

		if (portalId != that.portalId) return false;
		if (emailId != that.emailId) return false;
		if (portalContactId != that.portalContactId) return false;

		return true;
	}

	@Override
	public int hashCode() {
		int result = (int) portalId;
		result = 31 * result + emailId;
		result = 31 * result + (int) portalContactId;
		return result;
	}
}


