package br.org.roger.spring.domain;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * FlSegmentoNegocio generated by hbm2java
 */
@SuppressWarnings("serial")
@javax.persistence.Entity
@Table(name = "FL_SEGMENTO_NEGOCIO")
@NamedQueries({})
public class SegmentoNegocio implements java.io.Serializable {

	public static final class Queries {
	}

	@Id
	@Column(name = "COD_SEGMENTO_NEGOCIO", unique = true, nullable = false, precision = 9, scale = 0)
	private Long id;


	@Column(name = "NRO_SEGMENTO_NEGOCIO", precision = 2, scale = 0)
	private Integer nroSegmentoNegocio;

	@Column(name = "DESC_SEGMENTO_NEGOCIO", length = 50)
	private String descSegmentoNegocio;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "segmentoNegocio")
	private Set<UnidadeNegocio> unidadeNegocios = new HashSet<UnidadeNegocio>(0);

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescSegmentoNegocio() {
        return descSegmentoNegocio;
    }

    public void setDescSegmentoNegocio(String descSegmentoNegocio) {
        this.descSegmentoNegocio = descSegmentoNegocio;
    }

    public Set<UnidadeNegocio> getUnidadeNegocios() {
        return unidadeNegocios;
    }

    public void setUnidadeNegocios(Set<UnidadeNegocio> unidadeNegocios) {
        this.unidadeNegocios = unidadeNegocios;
    }

    public Integer getNroSegmentoNegocio() {
        return nroSegmentoNegocio;
    }

    public void setNroSegmentoNegocio(Integer nroSegmentoNegocio) {
        this.nroSegmentoNegocio = nroSegmentoNegocio;
    }
}
